version: "3.8"

services:
  mcp-server:
    build:
      context: ./aci-mcp
      dockerfile: Dockerfile
    container_name: mcp-server
    env_file:
      - .env
    ports:
      - "8002:8002"


  # ──────────────────────────────────────────────────────────────────────
  # Your agent service (unchanged)
  # ──────────────────────────────────────────────────────────────────────
  agent-service:
    build:
      context: .
      dockerfile: Dockerfile.agent-service
    container_name: agent-service
    depends_on:
      - mcp-server
    env_file:
      - .env
    ports:
      - "8001:8001"


# # docker-compose.yml

# services:
#   mcp-server:
#     build:
#       context: ./mcp_server  # Directory containing the Dockerfile.mcp-server
#       dockerfile: Dockerfile.mcp-server
#     container_name: mcp-server
#     ports:
#       - "8002:8002"
#     env_file:
#       - .env
#     # environment variables can be set here if needed
#     # environment:
#     #   - MCP_SERVER_PORT=8002

#   agent-service:
#     build:
#       context: .
#       dockerfile: Dockerfile.agent-service
#     container_name: agent-service
#     depends_on:
#       - mcp-server
#     ports:
#       - "8001:8001"
