

services:
  mcp-server:
    build:
      context: ./mcp_server  # Directory containing the Dockerfile.mcp-server
      dockerfile: Dockerfile.mcp-server
    container_name: mcp-server
    ports:
      - "8002:8002"
    env_file:
      - .env

  agent-service:
    build:
      context: .                                   
      dockerfile: ./agent_service/Dockerfile
    container_name: agent-service
    depends_on:
      - mcp-server
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./agent_service/tmp/marketing_agent_outputs:/tmp/marketing_agent_outputs