apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: ogpt
spec:
  type: NodePort
  selector:
    app: agent-server
  ports:
  - protocol: TCP
    port: 4881
    targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-server
  namespace: ogpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-server
  template:
    metadata:
      labels:
        app: agent-server
    spec:
      containers:
      - name: agent-server
        image: sapdai/refd:agent-service-v1
        imagePullPolicy: Always
        env:
        - name: LOCAL_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: LOCAL_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LOCAL_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOCAL_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LOCAL_SERVICE_NAME
          value: "vllm"
        - name: LOCAL_REST_SERVER_PORT
          value: "8001"
        - name: LLM_ID
          value: "meta-llama/Llama-3.1-8B-Instruct"
        - name: MAX_NEW_TOKENS
          value: "1000"
        - name: TEMPERATURE
          value: "0.2"
        - name: TOP_P
          value: "0.95"
        - name: REPETITION_PENALTY
          value: "1.0"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-all
              key: HF_TOKEN
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        command: [ "bash", "-c" ]
        args:
        - './agent_service/start_service.sh'
        ports:
        - containerPort: 8001
      imagePullSecrets:
      - name: dockerhub
      nodeSelector:
        nodetype: gaudi2-118
      terminationGracePeriodSeconds: 5
