apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app: {{ .Release.Name }}-agent-svc
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-agent-server
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.agent.servicePort }}
      targetPort: {{ .Values.agent.containerPort }}
