apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-classifier
  labels:
    app: {{ .Release.Name }}-classifier-svc
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-classifier-server
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.classifier.servicePort }}
      targetPort: {{ .Values.classifier.containerPort }}
