apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-classifier-server
spec:
  replicas: {{ .Values.classifier.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-classifier-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-classifier-server
    spec:
      containers:
        - name: classifier
          image: "{{ .Values.classifier.image.repository }}:{{ .Values.classifier.image.tag }}"
          imagePullPolicy: {{ .Values.classifier.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.classifier.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.classifier.resources.requests.cpu }}
              memory: {{ .Values.classifier.resources.requests.memory }}
            limits:
              cpu: {{ .Values.classifier.resources.limits.cpu }}
              memory: {{ .Values.classifier.resources.limits.memory }}
      imagePullSecrets:
        - name: dockerhub  # Or remove if you don’t need a pull secret
      nodeSelector:
{{- range $key, $value := .Values.classifier.nodeSelector }}
        {{ $key }}: "{{ $value }}"
{{- end }}
      terminationGracePeriodSeconds: 5
