apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-stack.classifierFullname" . }}
  labels:
    app: {{ include "agent-stack.classifierName" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "agent-stack.classifierName" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.classifier.servicePort }}
      targetPort: {{ .Values.classifier.containerPort }}
