namespace: ogpt

classifier:
  replicaCount: 1
  image:
    repository: sapdai/refd
    tag: agent-poc-classifier
    pullPolicy: Always
  containerPort: 8000
  servicePort: 8000
  nodeSelector:
    nodetype: gaudi2-118
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

agent:
  replicaCount: 1
  image:
    repository: sapdai/refd
    tag: agent-service-v3
    pullPolicy: Always
  containerPort: 8001
  servicePort: 4881
  configFile: "default.yaml"
  openaiSecret:
    enabled: true
    secretName: openai
    secretKey: OPENAI
  # Example environment variables
  env:
    LOCAL_SERVICE_NAME: "vllm"
    LOCAL_REST_SERVER_PORT: "8001"
    LLM_ID: "meta-llama/Llama-3.1-8B-Instruct"
    MAX_NEW_TOKENS: "1000"
    TEMPERATURE: "0.2"
    TOP_P: "0.95"
    REPETITION_PENALTY: "1.0"
  hfSecret:
    enabled: true
    secretName: hf-token-all
    secretKey: HF_TOKEN
  nodeSelector:
    nodetype: gaudi2-118
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"
